In [2]:
import pandas as pd

In [3]:
admission_df = pd.read_csv("../data/admission details.csv")
admission_df.columns = admission_df.columns.str.lower()
admission_df.rename(columns={
    "pt id":"pt_id",
    "doctor id":"doctor_id"
},inplace=True)

doctors_df = pd.read_csv("../data/doctors.csv")
doctors_df.columns = doctors_df.columns.str.lower()
doctors_df.rename(columns={
    "gender":"doctors_gender",
    "email":"doctors_email",
    "specialization":"doctors_specialization"
},inplace=True)

patient_df = pd.read_csv("../data/patient details.csv")
patient_df.columns = patient_df.columns.str.lower()
patient_df.rename(columns={
    "pt id":"pt_id",
    "name": "pt_name",
    "age": "pt_age",
    "sex": "pt_sex",
    "occupation": "pt_occupation",
    "level of education": "pt_level_of_education",
    "marital status": "pt_marital_status"
}, inplace=True)

risk_df = pd.read_csv("../data/risk factor.csv")
risk_df.columns = risk_df.columns.str.lower()
risk_df.rename(columns={"pt id":"pt_id"},inplace=True)

for df in [admission_df, doctors_df, patient_df, risk_df]:
    df.columns = df.columns.str.lower().str.strip().str.replace(" ", "_")

for df in [admission_df, doctors_df, patient_df, risk_df]:
    df[:] = df.apply(
        lambda col: col.str.strip().str.lower()
        if col.dtype == "str" else col
    )

In [4]:
#admission df check
admission_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1478 entries, 0 to 1477
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   pt_id               1478 non-null   int64
 1   admission_id        1478 non-null   int64
 2   admission_duration  1478 non-null   int64
 3   doctor_id           1478 non-null   str
 4   dama                1478 non-null   str
 5   reason_for_dama     276 non-null    str
 6   dead                1478 non-null   str
 7   cause_of_death      294 non-null    str
 8   ckd                 1478 non-null   str
 9   cause_ckd           326 non-null    str
 10  dialysis            1478 non-null   str
 11  no_of_sessions      25 non-null     float64
 12  stroke              1478 non-null   str
 13  dm                  1478 non-null   str
 14  cancer              1478 non-null   str
 15  type_of_cancer      32 non-null     str
 16  pud                 1478 non-null   str
dtypes: float64(1), int64(3), str(13)
memory usage: 239.5 KB

In [5]:
doctors_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   doctor_id               39 non-null     str
 1   doctor                  39 non-null     str
 2   doctors_gender          39 non-null     str
 3   doctors_email           39 non-null     str
 4   doctors_specialization  39 non-null     str
dtypes: str(5)
memory usage: 3.1 KB

In [17]:
doctors_df["doctor_id"].nunique()

39

In [18]:
admission_df["doctor_id"].nunique()

36

In [7]:
patient_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1478 entries, 0 to 1477
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   pt_id                  1478 non-null   int64
 1   pt_name                1478 non-null   str
 2   pt_age                 1473 non-null   float64
 3   pt_sex                 1478 non-null   str
 4   pt_occupation          1478 non-null   str
 5   pt_level_of_education  542 non-null    str
 6   pt_marital_status      1462 non-null   str
dtypes: float64(1), int64(1), str(5)
memory usage: 126.7 KB

In [8]:
risk_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1478 entries, 0 to 1477
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   pt_id       1478 non-null   int64
 1   alcohol_hx  1478 non-null   str
 2   tobacco_hx  1478 non-null   str
 3   nsaid_use   1478 non-null   str
dtypes: int64(1), str(3)
memory usage: 55.4 KB

In [9]:
admission_df = admission_df.merge(doctors_df,on="doctor_id",how="left")
admission_df = admission_df.merge(patient_df,on="pt_id",how="left")
admission_df = admission_df.merge(risk_df,on="pt_id",how="left")
admission_df.head()

,pt_id,admission_id,admission_duration,doctor_id,dama,reason_for_dama,dead,cause_of_death,ckd,cause_ckd,...,doctors_specialization,pt_name,pt_age,pt_sex,pt_occupation,pt_level_of_education,pt_marital_status,alcohol_hx,tobacco_hx,nsaid_use
0,1,101,16,d004,no,NaN,no,NaN,no,NaN,...,nephrology,bitrus daches,60.0,m,trading,NaN,married,no,no,yes
1,2,102,8,d030,no,NaN,no,NaN,no,NaN,...,anesthesiology,glory favor,60.0,m,retiree,NaN,married,no,no,yes
2,3,103,6,d030,no,NaN,no,NaN,no,NaN,...,anesthesiology,animasaun dayo,49.0,m,computer scientist,ba,married,yes,no,yes
3,4,104,13,d030,no,NaN,no,NaN,no,NaN,...,anesthesiology,fesobi tunde,78.0,m,retiree,NaN,married,no,no,yes
4,5,105,30,d030,no,NaN,no,NaN,no,NaN,...,anesthesiology,anetine lide,91.0,f,retiree,NaN,married,no,no,yes

In [10]:
admission_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1478 entries, 0 to 1477
Data columns (total 30 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   pt_id                   1478 non-null   int64
 1   admission_id            1478 non-null   int64
 2   admission_duration      1478 non-null   int64
 3   doctor_id               1478 non-null   str
 4   dama                    1478 non-null   str
 5   reason_for_dama         276 non-null    str
 6   dead                    1478 non-null   str
 7   cause_of_death          294 non-null    str
 8   ckd                     1478 non-null   str
 9   cause_ckd               326 non-null    str
 10  dialysis                1478 non-null   str
 11  no_of_sessions          25 non-null     float64
 12  stroke                  1478 non-null   str
 13  dm                      1478 non-null   str
 14  cancer                  1478 non-null   str
 15  type_of_cancer          32 non-null     str
 16  pud                     1478 non-null   str
 17  doctor                  1478 non-null   str
 18  doctors_gender          1478 non-null   str
 19  doctors_email           1478 non-null   str
 20  doctors_specialization  1478 non-null   str
 21  pt_name                 1478 non-null   str
 22  pt_age                  1473 non-null   float64
 23  pt_sex                  1478 non-null   str
 24  pt_occupation           1478 non-null   str
 25  pt_level_of_education   542 non-null    str
 26  pt_marital_status       1462 non-null   str
 27  alcohol_hx              1478 non-null   str
 28  tobacco_hx              1478 non-null   str
 29  nsaid_use               1478 non-null   str
dtypes: float64(2), int64(3), str(25)
memory usage: 496.8 KB

In [11]:
admission_df["pt_age"].unique()

array([60., 49., 78., 91., 66., 79., 47., 77., 64., 74., 62., 53., 54.,
       82., 19., 87., 50., 52., 70., 61., 73., 45., 20., 30., 65., 26.,
       67., 32., 18., 57., 46., 44., 28., 48., 40., 56., 42., 63., 39.,
       38., 75., 72., nan, 31., 25., 51., 22., 27., 33., 37., 68., 83.,
       43., 35., 69., 90., 85., 29., 71., 41., 55., 59., 76., 81., 58.,
       36., 84., 24., 34., 80., 23., 16., 86., 94., 89., 21., 15.])

In [12]:
age_map = {
    **dict.fromkeys(range(0, 18), "0-17"),
    **dict.fromkeys(range(18, 30), "18-29"),
    **dict.fromkeys(range(30, 45), "30-44"),
    **dict.fromkeys(range(45, 60), "45-59"),
    **dict.fromkeys(range(60, 75), "60-74"),
    **dict.fromkeys(range(75, 101), "75+")
}

admission_df["age_range"] = admission_df["pt_age"].map(age_map)

group_map = {
    "0-17": "Under 18",
    "18-29": "Young adults",
    "30-44": "Adults",
    "45-59": "Middle-aged adults",
    "60-74": "Older adults",
    "75+": "Elderly adults"
}

admission_df["age_group"] = admission_df["age_range"].map(group_map)

admission_df[["pt_age", "age_range", "age_group"]].head(20)

    pt_age age_range           age_group
0     60.0     60-74        Older adults
1     60.0     60-74        Older adults
2     49.0     45-59  Middle-aged adults
3     78.0       75+      Elderly adults
4     91.0       75+      Elderly adults
5     66.0     60-74        Older adults
6     79.0       75+      Elderly adults
7     60.0     60-74        Older adults
8     47.0     45-59  Middle-aged adults
9     77.0       75+      Elderly adults
10    64.0     60-74        Older adults
11    60.0     60-74        Older adults
12    74.0     60-74        Older adults
13    64.0     60-74        Older adults
14    62.0     60-74        Older adults
15    60.0     60-74        Older adults
16    53.0     45-59  Middle-aged adults
17    54.0     45-59  Middle-aged adults
18    82.0       75+      Elderly adults
19    19.0     18-29        Young adults

In [13]:
admission_map = {
    **dict.fromkeys(range(1, 4), "Short stay"),
    **dict.fromkeys(range(4, 8), "Moderate stay"),
    **dict.fromkeys(range(8, 15), "Extended stay"),
    **dict.fromkeys(range(15, 31), "Long stay"),
    **dict.fromkeys(range(31, 101), "Very long stay")
}

admission_df["admission_group"] = admission_df["admission_duration"].map(admission_map)

admission_df[["admission_duration", "admission_group"]].head(20)

    admission_duration admission_group
0                   16       Long stay
1                    8   Extended stay
2                    6   Moderate stay
3                   13   Extended stay
4                   30       Long stay
5                    7   Moderate stay
6                   34  Very long stay
7                   26       Long stay
8                   19       Long stay
9                   15       Long stay
10                  22       Long stay
11                  13   Extended stay
12                   7   Moderate stay
13                   5   Moderate stay
14                  29       Long stay
15                  11   Extended stay
16                  18       Long stay
17                   9   Extended stay
18                   2      Short stay
19                  20       Long stay

In [14]:
admission_df.columns.to_list()

['pt_id',
 'admission_id',
 'admission_duration',
 'doctor_id',
 'dama',
 'reason_for_dama',
 'dead',
 'cause_of_death',
 'ckd',
 'cause_ckd',
 'dialysis',
 'no_of_sessions',
 'stroke',
 'dm',
 'cancer',
 'type_of_cancer',
 'pud',
 'doctor',
 'doctors_gender',
 'doctors_email',
 'doctors_specialization',
 'pt_name',
 'pt_age',
 'pt_sex',
 'pt_occupation',
 'pt_level_of_education',
 'pt_marital_status',
 'alcohol_hx',
 'tobacco_hx',
 'nsaid_use',
 'age_range',
 'age_group',
 'admission_group']

In [15]:
admission_df.to_parquet("../data/cleaned_merged_df.parquet")